# fly.toml app configuration file generated for playbuddy-scraper on 2025-07-30T08:38:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playbuddy-scraper'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
