# fly.toml app configuration file generated for playbuddy-scraper on 2025-07-30T08:38:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'playbuddy-scraper'
primary_region = 'ewr'

[build]

[auto_stop]
  enabled = true
  timeout = "1h"

[http_service]
  internal_port = 8082
  force_https = true
  min_machines_running = 0
  auto_start_machines = false
  auto_stop_machines = "off"
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
