[[redirects]]
  from = "https://kinkbuddy.org"
  to = "https://playbuddy.me"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build]
command = "cd ../common && npm i && cd ../playbuddy-web && npm i && npx tsc -b && npx vite build"
base = "playbuddy-web"
publish = "dist"